### ISSUE TITLE
README quickstart?

### ISSUE THREAD

**Issue by hxegon** [Shougo/dein.vim#28]
# Problems summary
Can't figure out how to use dein.vim from readme

## Expected
README.md to have a quickstart with at least one example of installing a plugin.

Not trying to troll or anything, but as someone who has used vundle/pathogen for 2-ish years; this is extremely vague, and seems easy to fix.

**Comment by symbolix** [comment]
Yeah. That would be great. My current setup is relying on **Neobundle** right now, and I am looking into migrating this to **dein.vim**. However, despite the similarities between the two plugins, I find it hard to get my head around and start the transition process due to lack of solid case studies and examples. Looking forward to see those. Thanks.

**Comment by Shougo** [comment]
I have added the example.

**Comment by hxegon** [comment]
Thanks so much! That really makes it clear.
